shop:
  image: dnhsoft/shopware:5.1.5
  links:
   - db
   - mailhog
  volumes:
   - "./../Local:/shopware/engine/Shopware/Plugins/Local"
  ports:
   - "8000:80"

db:
  image: tutum/mysql:5.6
  volumes:
   - ".database:/var/lib/mysql"
  environment:
   MYSQL_PASS: 123456


pma:
  image: dnhsoft/phpmyadmin:4.6.0
  links:
   - db
  ports:
   - "8001:80"

mailhog:
  image: mailhog/mailhog
  expose:
   - "1025"
   - "8025"
  ports:
   - "8025:8025"
