shop526:
  image: dnhsoft/shopware:5.2.6-php7
  links:
   - db
  ports:
   - "8526:80"
  environment:
   SWDB_DATABASE: shopware526


shop524:
  image: dnhsoft/shopware:5.2.4-php7
  links:
   - db
  ports:
   - "8524:80"
  environment:
   SWDB_DATABASE: shopware524
 

shop515:
  image: dnhsoft/shopware:5.1.5
  links:
   - db
  ports:
   - "8515:80"
  environment:
   SWDB_DATABASE: shopware515
   SWDB_USER: root


shop513:
  image: dnhsoft/shopware:5.1.3
  links:
   - db
  ports:
   - "8513:80"
  environment:
   SWDB_DATABASE: shopware513
   SWDB_USER: root

db:
  image: dnhsoft/mysql-utf8:5.7
  volumes:
   - ".db:/var/lib/mysql"

pma:
  image: dnhsoft/phpmyadmin:4.6.3
  links:
   - db
  ports:
   - "8001:80"
